const termsWithExplanations = {
    'React': 'A JavaScript library for building user interfaces.',
    'react': 'A JavaScript library for building user interfaces.',
    'JavaScript': 'A programming language commonly used in web development.',
    'javascript': 'A programming language commonly used in web development.',
    'Node.js': 'A JavaScript runtime built on Chrome\'s V8 engine.',
    'node.js': 'A JavaScript runtime built on Chrome\'s V8 engine.',
    'Java': 'A high-level, class-based, object-oriented programming language.',
    'java': 'A high-level, class-based, object-oriented programming language.',
    'HTML': 'The standard markup language for creating web pages.',
    'html': 'The standard markup language for creating web pages.',
    'CSS': 'A style sheet language used for describing the presentation of a document written in HTML or XML.',
    'css': 'A style sheet language used for describing the presentation of a document written in HTML or XML.',
    'API': 'Application Programming Interface, a set of rules for building software applications.',
    'api': 'Application Programming Interface, a set of rules for building software applications.',
    'JSON': 'JavaScript Object Notation, a lightweight data interchange format.',
    'json': 'JavaScript Object Notation, a lightweight data interchange format.',
    'Git': 'A version control system for tracking changes in computer files.',
    'git': 'A version control system for tracking changes in computer files.',
    'GitHub': 'A platform for version control and collaboration.',
    'github': 'A platform for version control and collaboration.',
    'Vue.js': 'A progressive JavaScript framework for building user interfaces.',
    'vue.js': 'A progressive JavaScript framework for building user interfaces.',
    'Angular': 'A platform for building mobile and desktop web applications.',
    'angular': 'A platform for building mobile and desktop web applications.',
    'Python': 'A high-level, interpreted programming language known for its readability.',
    'python': 'A high-level, interpreted programming language known for its readability.',
    'C++': 'A general-purpose programming language that is an extension of C.',
    'c++': 'A general-purpose programming language that is an extension of C.',
    'C#': 'A modern, object-oriented programming language developed by Microsoft.',
    'c#': 'A modern, object-oriented programming language developed by Microsoft.',
    'Swift': 'A powerful programming language for iOS and macOS development.',
    'swift': 'A powerful programming language for iOS and macOS development.',
    'SQL': 'Structured Query Language, used for managing databases.',
    'sql': 'Structured Query Language, used for managing databases.',
    'NoSQL': 'A database model that does not use a fixed schema.',
    'nosql': 'A database model that does not use a fixed schema.',
    'Game Engine': 'A software platform for the development of video games.',
    'game engine': 'A software platform for the development of video games.',
    'Unity': 'A cross-platform game engine developed by Unity Technologies.',
    'unity': 'A cross-platform game engine developed by Unity Technologies.',
    'Unreal Engine': 'A game engine developed by Epic Games.',
    'unreal engine': 'A game engine developed by Epic Games.',
    'JavaFX': 'A software platform for creating rich internet applications.',
    'javafx': 'A software platform for creating rich internet applications.',
    'Android': 'A mobile operating system based on a modified version of the Linux kernel.',
    'android': 'A mobile operating system based on a modified version of the Linux kernel.',
    'iOS': 'A mobile operating system created by Apple Inc. for its hardware.',
    'ios': 'A mobile operating system created by Apple Inc. for its hardware.',
    'Game Development': 'The process of creating a video game.',
    'game development': 'The process of creating a video game.',
    'OpenGL': 'A cross-language, cross-platform API for rendering 2D and 3D vector graphics.',
    'opengl': 'A cross-language, cross-platform API for rendering 2D and 3D vector graphics.',
    'DirectX': 'A set of application programming interfaces for handling tasks related to multimedia.',
    'directx': 'A set of application programming interfaces for handling tasks related to multimedia.',
    'Pixel': 'The smallest unit of a digital image or display.',
    'pixel': 'The smallest unit of a digital image or display.',
    'Shader': 'A set of software instructions used to calculate rendering effects.',
    'shader': 'A set of software instructions used to calculate rendering effects.',
    'NPC': 'Non-Playable Character, a character not controlled by the player.',
    'npc': 'Non-Playable Character, a character not controlled by the player.',
    'FPS': 'First-Person Shooter, a genre of video game that simulates weapon-based combat.',
    'fps': 'First-Person Shooter, a genre of video game that simulates weapon-based combat.',
    'RPG': 'Role-Playing Game, a genre of game where players assume the roles of characters.',
    'rpg': 'Role-Playing Game, a genre of game where players assume the roles of characters.',
    'MMO': 'Massively Multiplayer Online game, a game with a large number of players.',
    'mmo': 'Massively Multiplayer Online game, a game with a large number of players.',
    'VR': 'Virtual Reality, a simulated experience that can mimic physical presence.',
    'vr': 'Virtual Reality, a simulated experience that can mimic physical presence.',
    'AR': 'Augmented Reality, an interactive experience where real-world environments are enhanced.',
    'ar': 'Augmented Reality, an interactive experience where real-world environments are enhanced.',
    'Loot': 'Items that players can collect, often obtained from defeated enemies.',
    'loot': 'Items that players can collect, often obtained from defeated enemies.',
    'Spawn Point': 'A location where players or NPCs appear in the game world.',
    'spawn point': 'A location where players or NPCs appear in the game world.',
    'Quest': 'A task or set of tasks that players must complete.',
    'quest': 'A task or set of tasks that players must complete.',
    'Boss': 'A powerful enemy character, usually encountered at the end of a level or game.',
    'boss': 'A powerful enemy character, usually encountered at the end of a level or game.',
    'Level Up': 'To increase a character’s experience or abilities.',
    'level up': 'To increase a character’s experience or abilities.',
    'Gamer': 'A person who plays video games.',
    'gamer': 'A person who plays video games.',
    'E-sports': 'Organized, multiplayer video game competitions.',
    'e-sports': 'Organized, multiplayer video game competitions.',
    'Cheat Code': 'A code used to gain an advantage in a game.',
    'cheat code': 'A code used to gain an advantage in a game.',
    'Patch': 'An update to a game that fixes bugs or adds content.',
    'patch': 'An update to a game that fixes bugs or adds content.',
    'Beta': 'A version of a game that is still in development but available for testing.',
    'beta': 'A version of a game that is still in development but available for testing.',
    'Alpha': 'The first phase of testing in game development.',
    'alpha': 'The first phase of testing in game development.',
    'DLC': 'Downloadable Content, additional content created for a game.',
    'dlc': 'Downloadable Content, additional content created for a game.',
    'Player': 'A person who plays a video game.',
    'player': 'A person who plays a video game.',
    'Clutch': 'Performing well in a high-pressure situation.',
    'clutch': 'Performing well in a high-pressure situation.',
    'Sandbox': 'A game where players can create and explore freely.',
    'sandbox': 'A game where players can create and explore freely.',
    'Multiplayer': 'A mode in which multiple players can play a game together.',
    'multiplayer': 'A mode in which multiple players can play a game together.',
    'Single Player': 'A mode where one player plays alone against the game.',
    'single player': 'A mode where one player plays alone against the game.',
    'Speedrun': 'Completing a game as quickly as possible.',
    'speedrun': 'Completing a game as quickly as possible.',
    'Boss Fight': 'A battle against a powerful enemy character.',
    'boss fight': 'A battle against a powerful enemy character.',
    'Skill Tree': 'A progression system for unlocking abilities in a game.',
    'skill tree': 'A progression system for unlocking abilities in a game.',
    'Crafting': 'Creating items or equipment using materials found in the game.',
    'crafting': 'Creating items or equipment using materials found in the game.',
    'Loot Box': 'A virtual item that contains random rewards.',
    'loot box': 'A virtual item that contains random rewards.',
    'Game Mechanics': 'Rules and systems that govern gameplay.',
    'game mechanics': 'Rules and systems that govern gameplay.',
    'Achievements': 'Tasks that players can complete to earn rewards.',
    'achievements': 'Tasks that players can complete to earn rewards.',
    'Health Bar': 'A visual representation of a character’s health.',
    'health bar': 'A visual representation of a character’s health.',
    'Mana': 'A resource used for casting spells or abilities.',
    'mana': 'A resource used for casting spells or abilities.',
    'Stamina': 'A resource that determines how long a character can perform actions.',
    'stamina': 'A resource that determines how long a character can perform actions.',
    'Character Customization': 'The ability to change a character’s appearance or abilities.',
    'character customization': 'The ability to change a character’s appearance or abilities.',
    'Hit Points': 'A measure of a character’s health in a game.',
    'hit points': 'A measure of a character’s health in a game.',
    'Stealth': 'A gameplay style focused on avoiding detection.',
    'stealth': 'A gameplay style focused on avoiding detection.',
    'Open World': 'A game design that allows players to explore a large virtual world.',
    'open world': 'A game design that allows players to explore a large virtual world.',
    'Save Point': 'A location in a game where progress can be saved.',
    'save point': 'A location in a game where progress can be saved.',
    'Respawn': 'To come back to life in a game after being defeated.',
    'respawn': 'To come back to life in a game after being defeated.',
    'Combo': 'A sequence of attacks or moves executed in quick succession.',
    'combo': 'A sequence of attacks or moves executed in quick succession.',
    'Fiction': 'Literary or cinematic narrative created from imagination.',
    'fiction': 'Literary or cinematic narrative created from imagination.',
    'Lore': 'The backstory and history of a game world.',
    'lore': 'The backstory and history of a game world.',
    'Clans': 'Groups of players who come together for a common goal.',
    'clans': 'Groups of players who come together for a common goal.',
    'Game Over': 'A screen or message indicating the end of a game.',
    'game over': 'A screen or message indicating the end of a game.',
    'Difficulty Level': 'A measure of how challenging a game is.',
    'difficulty level': 'A measure of how challenging a game is.',
    'Voice Acting': 'Performing the voice of a character in a game.',
    'voice acting': 'Performing the voice of a character in a game.',
    'Puzzle': 'A game element that requires problem-solving skills.',
    'puzzle': 'A game element that requires problem-solving skills.',
    'Cutscene': 'A non-interactive sequence in a game used to advance the story.',
    'cutscene': 'A non-interactive sequence in a game used to advance the story.',
    'Fan Base': 'A community of enthusiasts around a game or franchise.',
    'fan base': 'A community of enthusiasts around a game or franchise.',
    'Franchise': 'A series of related products, such as games or films.',
    'franchise': 'A series of related products, such as games or films.',
    'Expansion Pack': 'A type of DLC that adds significant content to a game.',
    'expansion pack': 'A type of DLC that adds significant content to a game.',
    'Backstory': 'The history of a character or event in a narrative.',
    'backstory': 'The history of a character or event in a narrative.',
    'Beta Testing': 'The phase in which a game is tested by users before release.',
    'beta testing': 'The phase in which a game is tested by users before release.',
    'Early Access': 'A funding model where players can play a game before its full release.',
    'early access': 'A funding model where players can play a game before its full release.',
    'Speedrun': 'Completing a game or level in the shortest time possible.',
    'speedrun': 'Completing a game or level in the shortest time possible.',
    'World Building': 'The process of creating an imaginary world for a narrative.',
    'world building': 'The process of creating an imaginary world for a narrative.',
    'Player vs Player': 'A mode where players compete against each other.',
    'player vs player': 'A mode where players compete against each other.',
    'Player vs Environment': 'A mode where players compete against the game itself.',
    'player vs environment': 'A mode where players compete against the game itself.',
    'Crafting': 'Creating items using collected resources.',
    'crafting': 'Creating items using collected resources.',
    'Loot Drop': 'An item that is randomly dropped by defeated enemies.',
    'loot drop': 'An item that is randomly dropped by defeated enemies.',
    'Mod': 'A modification made to a game by players.',
    'mod': 'A modification made to a game by players.',
    'Ranking': 'A system of grading players based on their performance.',
    'ranking': 'A system of grading players based on their performance.',
    'Tournament': 'A competition between players or teams.',
    'tournament': 'A competition between players or teams.',
    'Hack': 'To manipulate or alter a game or system in an unauthorized manner.',
    'hack': 'To manipulate or alter a game or system in an unauthorized manner.',
    'Glitch': 'An unintended error in a game that can be exploited.',
    'glitch': 'An unintended error in a game that can be exploited.',
    'Combo Breaker': 'A move that interrupts an opponent’s combo.',
    'combo breaker': 'A move that interrupts an opponent’s combo.',
    'End Game': 'The final part of a game.',
    'end game': 'The final part of a game.',
    'Narrative': 'The storyline or plot of a game.',
    'narrative': 'The storyline or plot of a game.',
    'AI': 'Artificial Intelligence, programming that simulates human behavior in games.',
    'ai': 'Artificial Intelligence, programming that simulates human behavior in games.',
    'Gacha': 'A monetization system that involves random item drops.',
    'gacha': 'A monetization system that involves random item drops.',
    'Minigame': 'A small game within a larger game.',
    'minigame': 'A small game within a larger game.',
    'Respawn Timer': 'The time it takes for a player to re-enter the game after being eliminated.',
    'respawn timer': 'The time it takes for a player to re-enter the game after being eliminated.',
    'Skill Based Matchmaking': 'A system that matches players of similar skill levels.',
    'skill based matchmaking': 'A system that matches players of similar skill levels.',
    'Buff': 'A temporary increase in a character’s abilities.',
    'buff': 'A temporary increase in a character’s abilities.',
    'Debuff': 'A temporary decrease in a character’s abilities.',
    'debuff': 'A temporary decrease in a character’s abilities.',
    'Achievements': 'Tasks or milestones in a game that players can complete for rewards.',
    'achievements': 'Tasks or milestones in a game that players can complete for rewards.',
};

export default termsWithExplanations;

